// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateHelloworldRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHelloworldRequest) Reset()         { *m = CreateHelloworldRequest{} }
func (m *CreateHelloworldRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHelloworldRequest) ProtoMessage()    {}
func (*CreateHelloworldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *CreateHelloworldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHelloworldRequest.Unmarshal(m, b)
}
func (m *CreateHelloworldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHelloworldRequest.Marshal(b, m, deterministic)
}
func (m *CreateHelloworldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHelloworldRequest.Merge(m, src)
}
func (m *CreateHelloworldRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHelloworldRequest.Size(m)
}
func (m *CreateHelloworldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHelloworldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHelloworldRequest proto.InternalMessageInfo

type CreateHelloworldReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHelloworldReply) Reset()         { *m = CreateHelloworldReply{} }
func (m *CreateHelloworldReply) String() string { return proto.CompactTextString(m) }
func (*CreateHelloworldReply) ProtoMessage()    {}
func (*CreateHelloworldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *CreateHelloworldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHelloworldReply.Unmarshal(m, b)
}
func (m *CreateHelloworldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHelloworldReply.Marshal(b, m, deterministic)
}
func (m *CreateHelloworldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHelloworldReply.Merge(m, src)
}
func (m *CreateHelloworldReply) XXX_Size() int {
	return xxx_messageInfo_CreateHelloworldReply.Size(m)
}
func (m *CreateHelloworldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHelloworldReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHelloworldReply proto.InternalMessageInfo

type UpdateHelloworldRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHelloworldRequest) Reset()         { *m = UpdateHelloworldRequest{} }
func (m *UpdateHelloworldRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHelloworldRequest) ProtoMessage()    {}
func (*UpdateHelloworldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *UpdateHelloworldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHelloworldRequest.Unmarshal(m, b)
}
func (m *UpdateHelloworldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHelloworldRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHelloworldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHelloworldRequest.Merge(m, src)
}
func (m *UpdateHelloworldRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHelloworldRequest.Size(m)
}
func (m *UpdateHelloworldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHelloworldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHelloworldRequest proto.InternalMessageInfo

type UpdateHelloworldReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHelloworldReply) Reset()         { *m = UpdateHelloworldReply{} }
func (m *UpdateHelloworldReply) String() string { return proto.CompactTextString(m) }
func (*UpdateHelloworldReply) ProtoMessage()    {}
func (*UpdateHelloworldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *UpdateHelloworldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHelloworldReply.Unmarshal(m, b)
}
func (m *UpdateHelloworldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHelloworldReply.Marshal(b, m, deterministic)
}
func (m *UpdateHelloworldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHelloworldReply.Merge(m, src)
}
func (m *UpdateHelloworldReply) XXX_Size() int {
	return xxx_messageInfo_UpdateHelloworldReply.Size(m)
}
func (m *UpdateHelloworldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHelloworldReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHelloworldReply proto.InternalMessageInfo

type DeleteHelloworldRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHelloworldRequest) Reset()         { *m = DeleteHelloworldRequest{} }
func (m *DeleteHelloworldRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHelloworldRequest) ProtoMessage()    {}
func (*DeleteHelloworldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4}
}

func (m *DeleteHelloworldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHelloworldRequest.Unmarshal(m, b)
}
func (m *DeleteHelloworldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHelloworldRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHelloworldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHelloworldRequest.Merge(m, src)
}
func (m *DeleteHelloworldRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHelloworldRequest.Size(m)
}
func (m *DeleteHelloworldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHelloworldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHelloworldRequest proto.InternalMessageInfo

type DeleteHelloworldReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHelloworldReply) Reset()         { *m = DeleteHelloworldReply{} }
func (m *DeleteHelloworldReply) String() string { return proto.CompactTextString(m) }
func (*DeleteHelloworldReply) ProtoMessage()    {}
func (*DeleteHelloworldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{5}
}

func (m *DeleteHelloworldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHelloworldReply.Unmarshal(m, b)
}
func (m *DeleteHelloworldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHelloworldReply.Marshal(b, m, deterministic)
}
func (m *DeleteHelloworldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHelloworldReply.Merge(m, src)
}
func (m *DeleteHelloworldReply) XXX_Size() int {
	return xxx_messageInfo_DeleteHelloworldReply.Size(m)
}
func (m *DeleteHelloworldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHelloworldReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHelloworldReply proto.InternalMessageInfo

type GetHelloworldRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloworldRequest) Reset()         { *m = GetHelloworldRequest{} }
func (m *GetHelloworldRequest) String() string { return proto.CompactTextString(m) }
func (*GetHelloworldRequest) ProtoMessage()    {}
func (*GetHelloworldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{6}
}

func (m *GetHelloworldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloworldRequest.Unmarshal(m, b)
}
func (m *GetHelloworldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloworldRequest.Marshal(b, m, deterministic)
}
func (m *GetHelloworldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloworldRequest.Merge(m, src)
}
func (m *GetHelloworldRequest) XXX_Size() int {
	return xxx_messageInfo_GetHelloworldRequest.Size(m)
}
func (m *GetHelloworldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloworldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloworldRequest proto.InternalMessageInfo

type GetHelloworldReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloworldReply) Reset()         { *m = GetHelloworldReply{} }
func (m *GetHelloworldReply) String() string { return proto.CompactTextString(m) }
func (*GetHelloworldReply) ProtoMessage()    {}
func (*GetHelloworldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{7}
}

func (m *GetHelloworldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloworldReply.Unmarshal(m, b)
}
func (m *GetHelloworldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloworldReply.Marshal(b, m, deterministic)
}
func (m *GetHelloworldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloworldReply.Merge(m, src)
}
func (m *GetHelloworldReply) XXX_Size() int {
	return xxx_messageInfo_GetHelloworldReply.Size(m)
}
func (m *GetHelloworldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloworldReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloworldReply proto.InternalMessageInfo

type ListHelloworldRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHelloworldRequest) Reset()         { *m = ListHelloworldRequest{} }
func (m *ListHelloworldRequest) String() string { return proto.CompactTextString(m) }
func (*ListHelloworldRequest) ProtoMessage()    {}
func (*ListHelloworldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{8}
}

func (m *ListHelloworldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHelloworldRequest.Unmarshal(m, b)
}
func (m *ListHelloworldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHelloworldRequest.Marshal(b, m, deterministic)
}
func (m *ListHelloworldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHelloworldRequest.Merge(m, src)
}
func (m *ListHelloworldRequest) XXX_Size() int {
	return xxx_messageInfo_ListHelloworldRequest.Size(m)
}
func (m *ListHelloworldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHelloworldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHelloworldRequest proto.InternalMessageInfo

type ListHelloworldReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHelloworldReply) Reset()         { *m = ListHelloworldReply{} }
func (m *ListHelloworldReply) String() string { return proto.CompactTextString(m) }
func (*ListHelloworldReply) ProtoMessage()    {}
func (*ListHelloworldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{9}
}

func (m *ListHelloworldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHelloworldReply.Unmarshal(m, b)
}
func (m *ListHelloworldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHelloworldReply.Marshal(b, m, deterministic)
}
func (m *ListHelloworldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHelloworldReply.Merge(m, src)
}
func (m *ListHelloworldReply) XXX_Size() int {
	return xxx_messageInfo_ListHelloworldReply.Size(m)
}
func (m *ListHelloworldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHelloworldReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListHelloworldReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateHelloworldRequest)(nil), "api.helloworld.CreateHelloworldRequest")
	proto.RegisterType((*CreateHelloworldReply)(nil), "api.helloworld.CreateHelloworldReply")
	proto.RegisterType((*UpdateHelloworldRequest)(nil), "api.helloworld.UpdateHelloworldRequest")
	proto.RegisterType((*UpdateHelloworldReply)(nil), "api.helloworld.UpdateHelloworldReply")
	proto.RegisterType((*DeleteHelloworldRequest)(nil), "api.helloworld.DeleteHelloworldRequest")
	proto.RegisterType((*DeleteHelloworldReply)(nil), "api.helloworld.DeleteHelloworldReply")
	proto.RegisterType((*GetHelloworldRequest)(nil), "api.helloworld.GetHelloworldRequest")
	proto.RegisterType((*GetHelloworldReply)(nil), "api.helloworld.GetHelloworldReply")
	proto.RegisterType((*ListHelloworldRequest)(nil), "api.helloworld.ListHelloworldRequest")
	proto.RegisterType((*ListHelloworldReply)(nil), "api.helloworld.ListHelloworldReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x45, 0x04, 0x0f, 0x03, 0x2e, 0x4b, 0xdc, 0x5a, 0xec, 0x45, 0xa8, 0x8a, 0xb7, 0x2c, 0xb8,
	0x47, 0x6f, 0x2a, 0xe8, 0xc1, 0x83, 0x08, 0x1e, 0x14, 0x2f, 0x59, 0x3a, 0x60, 0x61, 0x24, 0x63,
	0x1b, 0x91, 0xfc, 0x6c, 0xff, 0x81, 0x44, 0xc4, 0xd0, 0x4c, 0x42, 0x6f, 0xe5, 0x7d, 0xf4, 0xb5,
	0xef, 0x25, 0xb0, 0x7c, 0x43, 0x22, 0xfb, 0x65, 0x07, 0xea, 0x34, 0x0f, 0xd6, 0x59, 0xb5, 0x30,
	0xdc, 0xeb, 0x88, 0xb6, 0x47, 0x50, 0x5f, 0x0f, 0x68, 0x1c, 0xde, 0xfd, 0x63, 0x8f, 0xf8, 0xf1,
	0x89, 0xa3, 0x6b, 0x6b, 0xa8, 0x24, 0xc5, 0xe4, 0x83, 0xe7, 0x89, 0xbb, 0x92, 0x47, 0x52, 0x7f,
	0x9e, 0x1b, 0x24, 0x2c, 0x78, 0x24, 0x15, 0x3c, 0x87, 0xb0, 0xba, 0x45, 0x27, 0x0d, 0x2b, 0x50,
	0x09, 0x1e, 0xd4, 0x35, 0x54, 0xf7, 0xfd, 0x98, 0x91, 0x57, 0x70, 0x90, 0x12, 0x4c, 0xfe, 0xe2,
	0x7b, 0x17, 0x20, 0x62, 0x6a, 0x0b, 0xcb, 0xf4, 0x6f, 0xd5, 0xb9, 0x9e, 0xb6, 0xa5, 0x0b, 0x55,
	0x35, 0x67, 0xf3, 0x42, 0x26, 0x1f, 0x32, 0xd2, 0x76, 0x64, 0x46, 0xa1, 0x5a, 0x99, 0x91, 0x2d,
	0x3a, 0x64, 0xa4, 0x6d, 0xca, 0x8c, 0xc2, 0x14, 0x32, 0x23, 0x3b, 0x8c, 0x7a, 0x86, 0xfd, 0xc9,
	0x00, 0xea, 0x34, 0xf5, 0xe5, 0x76, 0x6b, 0xda, 0x19, 0x55, 0x78, 0xf5, 0x2b, 0x2c, 0xa6, 0x63,
	0x29, 0xf1, 0x4d, 0xd9, 0x95, 0x9b, 0x93, 0x39, 0x19, 0x93, 0xbf, 0xda, 0x40, 0x72, 0xfe, 0x1f,
	0x76, 0x5e, 0x8e, 0xdf, 0xbd, 0x61, 0x5e, 0x1b, 0xee, 0xd7, 0x11, 0xbf, 0x8c, 0x8f, 0xdb, 0xbd,
	0xdf, 0x9b, 0xb3, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x9a, 0xfa, 0x63, 0x4d, 0x03, 0x00,
	0x00,
}
